/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ardoisemagique;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionListener;

/**
 *
 * @author jbben
 */
public class GraphicalInterface extends javax.swing.JFrame implements MouseMotionListener {

    /**
     * Creates new form GraphicalInterface
     */
    Point pt = new Point();

    public GraphicalInterface() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       
        initComponents();
        addMouseMotionListener(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackendPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        delateButton = new javax.swing.JButton();
        squareButton = new javax.swing.JButton();
        roundButton = new javax.swing.JButton();
        redButton = new javax.swing.JButton();
        greenButton = new javax.swing.JButton();
        blueButton = new javax.swing.JButton();
        MenuBar = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        QuitMenuItem = new javax.swing.JMenuItem();
        DelateMenuItem = new javax.swing.JMenuItem();
        EditMenu = new javax.swing.JMenu();
        FormPointeurMenu = new javax.swing.JMenu();
        RoundMenuItem = new javax.swing.JMenuItem();
        SquareMenuItem = new javax.swing.JMenuItem();
        ColorPointeurMenu = new javax.swing.JMenu();
        RedMenuItem = new javax.swing.JMenuItem();
        GreenMenuBar = new javax.swing.JMenuItem();
        BlueMenuBar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ardoise Magique");

        BackendPanel.setBackground(new java.awt.Color(255, 255, 255));

        MenuPanel.setBackground(new java.awt.Color(153, 153, 153));

        delateButton.setBackground(new java.awt.Color(204, 204, 204));
        delateButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        delateButton.setForeground(new java.awt.Color(255, 0, 0));
        delateButton.setText("Effacer");
        delateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delateButtonActionPerformed(evt);
            }
        });

        squareButton.setBackground(new java.awt.Color(187, 187, 187));
        squareButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        squareButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\jbben\\Documents\\MES DOCUMENTS\\Programmation\\Programmes Java\\ArdoiseMagique\\squarePicture.png")); // NOI18N
        squareButton.setText("Carré");
        squareButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                squareButtonActionPerformed(evt);
            }
        });

        roundButton.setBackground(new java.awt.Color(187, 187, 187));
        roundButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        roundButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\jbben\\Documents\\MES DOCUMENTS\\Programmation\\Programmes Java\\ArdoiseMagique\\roundPicture.jpg")); // NOI18N
        roundButton.setText("Rond");
        roundButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roundButtonActionPerformed(evt);
            }
        });

        redButton.setBackground(new java.awt.Color(187, 187, 187));
        redButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        redButton.setForeground(new java.awt.Color(255, 0, 0));
        redButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\jbben\\Documents\\MES DOCUMENTS\\Programmation\\Programmes Java\\ArdoiseMagique\\redPicture.jpg")); // NOI18N
        redButton.setText("Rouge");
        redButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redButtonActionPerformed(evt);
            }
        });

        greenButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        greenButton.setForeground(new java.awt.Color(0, 255, 0));
        greenButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\jbben\\Documents\\MES DOCUMENTS\\Programmation\\Programmes Java\\ArdoiseMagique\\greenPicture.jpg")); // NOI18N
        greenButton.setText("Vert");
        greenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenButtonActionPerformed(evt);
            }
        });

        blueButton.setBackground(new java.awt.Color(187, 187, 187));
        blueButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        blueButton.setForeground(new java.awt.Color(0, 0, 255));
        blueButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\jbben\\Documents\\MES DOCUMENTS\\Programmation\\Programmes Java\\ArdoiseMagique\\bluePicture.png")); // NOI18N
        blueButton.setText("Bleu");
        blueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(delateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(squareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(roundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(redButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(greenButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(squareButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(delateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(roundButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(redButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(greenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(blueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout BackendPanelLayout = new javax.swing.GroupLayout(BackendPanel);
        BackendPanel.setLayout(BackendPanelLayout);
        BackendPanelLayout.setHorizontalGroup(
            BackendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BackendPanelLayout.setVerticalGroup(
            BackendPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackendPanelLayout.createSequentialGroup()
                .addComponent(MenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 685, Short.MAX_VALUE))
        );

        FileMenu.setText("Fichier");

        QuitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        QuitMenuItem.setText("Quitter");
        QuitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QuitMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(QuitMenuItem);

        DelateMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        DelateMenuItem.setText("Effacer");
        DelateMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelateMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(DelateMenuItem);

        MenuBar.add(FileMenu);

        EditMenu.setText("Edition");

        FormPointeurMenu.setText("Forme du pointeur");

        RoundMenuItem.setText("Rond");
        RoundMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RoundMenuItemActionPerformed(evt);
            }
        });
        FormPointeurMenu.add(RoundMenuItem);

        SquareMenuItem.setText("Carré");
        SquareMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SquareMenuItemActionPerformed(evt);
            }
        });
        FormPointeurMenu.add(SquareMenuItem);

        EditMenu.add(FormPointeurMenu);

        ColorPointeurMenu.setText("Couleur du pointeur");

        RedMenuItem.setIcon(new javax.swing.ImageIcon("C:\\Users\\jbben\\Documents\\MES DOCUMENTS\\Programmation\\Programmes Java\\ArdoiseMagique\\redPicture.jpg")); // NOI18N
        RedMenuItem.setText("Rouge");
        RedMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RedMenuItemActionPerformed(evt);
            }
        });
        ColorPointeurMenu.add(RedMenuItem);

        GreenMenuBar.setIcon(new javax.swing.ImageIcon("C:\\Users\\jbben\\Documents\\MES DOCUMENTS\\Programmation\\Programmes Java\\ArdoiseMagique\\greenPicture.jpg")); // NOI18N
        GreenMenuBar.setText("Vert");
        GreenMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GreenMenuBarActionPerformed(evt);
            }
        });
        ColorPointeurMenu.add(GreenMenuBar);

        BlueMenuBar.setIcon(new javax.swing.ImageIcon("C:\\Users\\jbben\\Documents\\MES DOCUMENTS\\Programmation\\Programmes Java\\ArdoiseMagique\\bluePicture.png")); // NOI18N
        BlueMenuBar.setText("Bleu");
        BlueMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueMenuBarActionPerformed(evt);
            }
        });
        ColorPointeurMenu.add(BlueMenuBar);

        EditMenu.add(ColorPointeurMenu);

        MenuBar.add(EditMenu);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackendPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackendPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void mouseMoved(MouseEvent e) {
        //nothing
    }

    public void mouseDragged(MouseEvent e) {
        Graphics g = getGraphics();
        g.setColor(pt.getColor());
        pt.x = e.getX();
        pt.y = e.getY();
        Color color = new Color(1f, 0f, 0f, .0f);

        if ((pt.getX() < 10 || pt.getX() > 1360) || (pt.getY() < 138 || pt.getY() > 725)) {
            g.setColor(color);
        }
        if (pt.getTypePoint().equals("round")) {
            g.fillOval(pt.x, pt.y, pt.getTaille(), pt.getTaille());
        }
        if (pt.getTypePoint().equals("square")) {
            g.fillRect(pt.x, pt.y, pt.getTaille(), pt.getTaille());
        }
        if (pt.getTypePoint() == null) {
            g.fillOval(pt.x, pt.y, pt.getTaille(), pt.getTaille());
        }

    }

    private void QuitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QuitMenuItemActionPerformed
        dispose();
    }//GEN-LAST:event_QuitMenuItemActionPerformed

    private void delateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delateButtonActionPerformed
        repaint();
    }//GEN-LAST:event_delateButtonActionPerformed

    private void DelateMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelateMenuItemActionPerformed
        repaint();
    }//GEN-LAST:event_DelateMenuItemActionPerformed

    private void redButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redButtonActionPerformed
        pt.color = Color.red;
    }//GEN-LAST:event_redButtonActionPerformed

    private void greenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenButtonActionPerformed
        pt.color = Color.green;
    }//GEN-LAST:event_greenButtonActionPerformed

    private void blueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueButtonActionPerformed
        pt.color = Color.blue;
    }//GEN-LAST:event_blueButtonActionPerformed

    private void RedMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RedMenuItemActionPerformed
        pt.color = Color.red;
    }//GEN-LAST:event_RedMenuItemActionPerformed

    private void GreenMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GreenMenuBarActionPerformed
        pt.color = Color.green;
    }//GEN-LAST:event_GreenMenuBarActionPerformed

    private void BlueMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueMenuBarActionPerformed
        pt.color = Color.blue;
    }//GEN-LAST:event_BlueMenuBarActionPerformed

    private void roundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roundButtonActionPerformed
        pt.typePoint = "round";

    }//GEN-LAST:event_roundButtonActionPerformed

    private void squareButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_squareButtonActionPerformed
        pt.typePoint = "square";
    }//GEN-LAST:event_squareButtonActionPerformed

    private void RoundMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RoundMenuItemActionPerformed
        pt.typePoint = "round";
    }//GEN-LAST:event_RoundMenuItemActionPerformed

    private void SquareMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SquareMenuItemActionPerformed
        pt.typePoint = "square";
    }//GEN-LAST:event_SquareMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphicalInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GraphicalInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackendPanel;
    private javax.swing.JMenuItem BlueMenuBar;
    private javax.swing.JMenu ColorPointeurMenu;
    private javax.swing.JMenuItem DelateMenuItem;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu FormPointeurMenu;
    private javax.swing.JMenuItem GreenMenuBar;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JMenuItem QuitMenuItem;
    private javax.swing.JMenuItem RedMenuItem;
    private javax.swing.JMenuItem RoundMenuItem;
    private javax.swing.JMenuItem SquareMenuItem;
    private javax.swing.JButton blueButton;
    private javax.swing.JButton delateButton;
    private javax.swing.JButton greenButton;
    private javax.swing.JButton redButton;
    private javax.swing.JButton roundButton;
    private javax.swing.JButton squareButton;
    // End of variables declaration//GEN-END:variables
}
